# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

block_cipher = None
root_dir = Path.cwd()
src_dir = root_dir / "src"

a = Analysis(
    [str(src_dir / "futaba" / "core" / "app.py")],
    pathex=[str(src_dir)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "futaba",
        "futaba.core",
        "futaba.core.config",
        "futaba.core.app",
        "futaba.tasks",
        "futaba.tasks.task_manager",
        "futaba.routing",
        "futaba.routing.model_router",
        "futaba.agent",
        "futaba.agent.controller",
        "futaba.agent.tools",
        "futaba.agent.hermes_bridge",
        "futaba.agent.hermes_tools",
        "futaba.memory",
        "futaba.memory.memory_manager",
        "futaba.performance",
        "futaba.performance.resource_manager",
        "futaba.security",
        "futaba.security.credentials",
        "futaba.ipc",
        "futaba.ipc.server",
        "futaba.voice",
        "futaba.voice.pipeline",
        "futaba.video",
        "futaba.video.pipeline",
        "futaba.ui",
        "futaba.ui.theme",
        "futaba.ui.manager",
        "futaba.ui.hud.hud_window",
        "futaba.ui.tray.tray_icon",
        "futaba.ui.settings.settings_dialog",
        "futaba.ui.dashboard.main_window",
        "futaba.bootstrap",
        "futaba.bootstrap.bootstrapper",
        "pydantic",
        "pydantic_core",
        "pydantic_settings",
        "yaml",
        "openai",
        "httpx",
        "websockets",
        "psutil",
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
        "qasync",
        "sqlite3",
        "win32gui",
        "win32con",
        "win32api",
        "win32process",
        "PIL",
        "PIL.Image",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Futaba',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
